language: node_js

services:
  - postgresql
addons:
  postgresql: '9.6'

script:
  - npm run lint
  - npm run coverage

jobs:
  include:
    - stage: test
      node_js: '10'
      after_success:
        - npm run coveralls
    - stage: test
      node_js: '8'
    - stage: release
      node_js: '10'
      script: skip
      branches:
        only:
          - master
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
