language: node_js

node_js:
  - "8"
  - "10"

services:
  - postgresql

addons:
  postgresql: "9.6"

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run coverage
      after_success:
        - npm run coveralls
    - stage: release
      node_js: "10"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
