language: node_js

os: linux
dist: xenial # required for postgres 10

env:
  - PGHOST=127.0.0.1

before_script:
  - psql -f util/create-databases.sql -U postgres

jobs:
  include:
    - stage: test
      name: 'Node.js 12 / Postgres 12'
      node_js: '12'
      services:
        - postgresql
      addons:
        postgresql: '12'
      script:
        - yarn lint
        - yarn nyc
      after_success:
        - yarn coveralls

    - stage: test
      name: 'Node.js 12 / Postgres 11'
      node_js: '12'
      services:
        - postgresql
      addons:
        postgresql: '11'
      script:
        - yarn mocha

    - stage: test
      name: 'Node.js 12 / Postgres 10'
      node_js: '12'
      services:
        - postgresql
      addons:
        postgresql: '10'
      script:
        - yarn mocha

    - stage: test
      name: 'Node.js 10 / Postgres 9.6'
      node_js: '10'
      services:
        - postgresql
      addons:
        postgresql: '9.6'
      script:
        - yarn mocha

    # - stage: release
    #   node_js: '10'
    #   script: skip
    #   branches:
    #     only:
    #       - master
    #   deploy:
    #     provider: script
    #     skip_cleanup: true
    #     script: npx semantic-release
