language: node_js

jobs:
  include:
    - stage: test
      dist: xenial # required for postgres 10
      node_js: "10"
      services:
        - postgresql
      addons:
        postgresql: "10"
      script:
        - npm run lint
        - npm run coverage
      after_success:
        - npm run coveralls
    - stage: test
      node_js: "8"
      services:
        - postgresql
      addons:
        postgresql: "9.6"
    - stage: release
      node_js: "10"
      script: skip
      branches:
        only:
          - master
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
