language: node_js

services:
  - postgresql
addons:
  postgresql: '9.6'

jobs:
  include:
    - stage: test
      node_js: '10'
      script:
        - npm run lint
        - npm run coverage
      after_success:
        - npm run coveralls
    - stage: test
      node_js: '8'
      script:
        - npm run coverage
    - stage: release
      node_js: '10'
      script: skip
      branches:
        only:
          - master
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
