version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: knorm-example

  knorm-example:
    build: .
    command: npm run start:docker
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
