version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: knorm-timestamps

  knorm-timestamps:
    build: .
    command: npm run test:mocha
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
